### ISSUE TITLE
Does Not Work With Node 6.10.x

### ISSUE THREAD

**Issue by alberto-brigandi** [capriza/syswide-cas#6]
Related to #1, the commit https://github.com/nodejs/node/commit/4e1a5a71c1 doesn't allow to load external certificates in node.

Since the commit has been added in [v6.10.0](https://github.com/nodejs/node/blob/0cca27b3ffb9fade34aac0ee77d020fb7cac0879/doc/changelogs/CHANGELOG_V6.md#6.10.0) and not in v6.11.0 the expression added in 30829c0516ad91ee93deca03951218394e935c0c should be modified to allow the use of the secure context trap from v6.10.0 and up

**Comment by fujifish** [comment]
Published version 5.3.0.
Thanks!
