### ISSUE TITLE
Is there a way to use this with macOS keychain root certificate storage?

### ISSUE THREAD

**Issue by aguynamedben** [capriza/syswide-cas#8]
I'm building a Node.js/Electron app. Some of our corporate users are behind company-managed, self-signed certificates. Presumably their machines are pre-installed with root certificates (maybe OS level? maybe browser level?).

Our app, built in Node.js, without using the unsafe [`NODE_TLS_REJECT_UNAUTHORIZED`](https://nodejs.org/api/cli.html#cli_node_tls_reject_unauthorized_value), rejects to domains behind the self-signed certificate with `self signed certificate in certificate chain`.

If the user is on macOS, their root certs (maybe including custom ones?) are stored in the Keychain Access app. I'd like my app to inherit whatever root certificates are in the user's Keychain Access, so my app can access services as the rest of their system would.

Any tips on setting this up? I don't think the certs are stored in a simple directory on macOS.

Thanks for making this library public and providing some education on this fairly obscure topic! :pray:

**Comment by aguynamedben** [comment]
There's some interesting discussion on runtime searching of system root certs over here: https://github.com/nodejs/node/pull/8334#issuecomment-243466945

**Comment by fujifish** [comment]
You can use whatever method you like to obtain the certificates and add them as a trusted CA during runtime using `syswidecas.addCAs` method.
I think a good option for your case is to use `security find-certificate -a -p` bash command to obtain all the certificates in the keychain, and then add them as trusted certificates (or just the ones you want)

**Comment by climam** [comment]
The easiest solution if you are building an electron application would be to make your http request using the browser api.

**Comment by aguynamedben** [comment]
@fujifish @climam Thank you both very much for the smart solutions. For now we added a UI interaction that lets the user trust self-signed certificates in certain situations, but these are better solutions we'll try out.

**Comment by gannons** [comment]
@aguynamedben how did this work out for you? I'm in a similar position and I'm curious what solution you settled upon?

**Comment by aguynamedben** [comment]
I think we ended up not using this library. We have a native app that makes network requests. In some cases those network requests are proxied (i.e. by an enterprise company) using a self-signed certificate. In the case where that happens, we reflect it to the user in the UI and ask them if it's okay (i.e. "Allow AcmeCo network requests with self-signed certificate?")

**Comment by gannons** [comment]
Thanks for the update. In the end we manually read the machine certificates and used them in the network calls. Likewise we did not use this library.
